const recipes = [
  {
    "idMeal": "52874",
    "strMeal": "Beef and Mustard Pie",
    "strCategory": "Beef",
    "strArea": "British",
    "strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
    "strTags": "Meat,Pie",
    "strYoutube": "https://www.youtube.com/watch?v=nMyBC9staMU",
    "strIngredient1": "Beef",
    "strIngredient2": "Plain Flour",
    "strIngredient3": "Rapeseed Oil",
    "strIngredient4": "Red Wine",
    "strIngredient5": "Beef Stock",
    "strIngredient6": "Onion",
    "strIngredient7": "Carrots",
    "strIngredient8": "Thyme",
    "strIngredient9": "Mustard",
    "strIngredient10": "Egg Yolks",
    "strIngredient11": "Puff Pastry",
    "strIngredient12": "Green Beans",
    "strIngredient13": "Butter",
    "strIngredient14": "Salt",
    "strIngredient15": "Pepper",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1kg",
    "strMeasure2": "2 tbs",
    "strMeasure3": "2 tbs",
    "strMeasure4": "200ml",
    "strMeasure5": "400ml",
    "strMeasure6": "1 finely sliced",
    "strMeasure7": "2 chopped",
    "strMeasure8": "3 sprigs",
    "strMeasure9": "2 tbs",
    "strMeasure10": "2 free-range",
    "strMeasure11": "400g",
    "strMeasure12": "300g",
    "strMeasure13": "25g",
    "strMeasure14": "pinch",
    "strMeasure15": "pinch",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002"
  },
  {
    "idMeal": "52878",
    "strMeal": "Beef and Oyster pie",
    "strCategory": "Beef",
    "strArea": "British",
    "strInstructions": "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
    "strTags": "Pie",
    "strYoutube": "https://www.youtube.com/watch?v=ONX74yP6JnI",
    "strIngredient1": "Beef",
    "strIngredient2": "Olive Oil",
    "strIngredient3": "Shallots",
    "strIngredient4": "Garlic",
    "strIngredient5": "Bacon",
    "strIngredient6": "Thyme",
    "strIngredient7": "Bay Leaf",
    "strIngredient8": "Stout",
    "strIngredient9": "Beef Stock",
    "strIngredient10": "Corn Flour",
    "strIngredient11": "Oysters",
    "strIngredient12": "Plain Flour",
    "strIngredient13": "Salt",
    "strIngredient14": "Butter",
    "strIngredient15": "Eggs",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "900g",
    "strMeasure2": "3 tbs",
    "strMeasure3": "3",
    "strMeasure4": "2 cloves minced",
    "strMeasure5": "125g",
    "strMeasure6": "1 tbs chopped",
    "strMeasure7": "2",
    "strMeasure8": "330ml",
    "strMeasure9": "400ml",
    "strMeasure10": "2 tbs",
    "strMeasure11": "8",
    "strMeasure12": "400g",
    "strMeasure13": "pinch",
    "strMeasure14": "250g",
    "strMeasure15": "To Glaze",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230"
  },
  {
    "idMeal": "52997",
    "strMeal": "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
    "strCategory": "Beef",
    "strArea": "Vietnamese",
    "strInstructions": "Add'l ingredients: mayonnaise, siracha\r\n\r\n1\r\n\r\nPlace rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water (2 cups for 4 servings) and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes. Keep covered off heat for at least 10 minutes or until ready to serve.\r\n\r\n2\r\n\r\nMeanwhile, wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime (for 4 servings, zest 1 lime and quarter both). Trim and halve cucumber lengthwise; thinly slice crosswise into half-moons. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\r\n\r\n3\r\n\r\nIn a medium bowl, combine cucumber, juice from half the lime, ¼ tsp sugar (½ tsp for 4 servings), and a pinch of salt. In a small bowl, combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and as much sriracha as you’d like. Season with salt and pepper.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring, until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar (4 tsp for 4 servings). Cook, breaking up meat into pieces, until beef is browned and cooked through, 4-5 minutes. Stir in soy sauce. Turn off heat; taste and season with salt and pepper.\r\n\r\n5\r\n\r\nFluff rice with a fork; stir in lime zest and 1 TBSP butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top. Top with a squeeze of lime juice. Drizzle with sriracha mayo.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg",
    "strYoutube": "",
    "strIngredient1": "Rice",
    "strIngredient2": "Onion",
    "strIngredient3": "Lime",
    "strIngredient4": "Garlic Clove",
    "strIngredient5": "Cucumber",
    "strIngredient6": "Carrots",
    "strIngredient7": "Ground Beef",
    "strIngredient8": "Soy Sauce",
    "strIngredient9": "",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "White",
    "strMeasure2": "1",
    "strMeasure3": "1",
    "strMeasure4": "3",
    "strMeasure5": "1",
    "strMeasure6": "3 oz ",
    "strMeasure7": "1 lb",
    "strMeasure8": "2 oz ",
    "strMeasure9": " ",
    "strMeasure10": " ",
    "strMeasure11": " ",
    "strMeasure12": " ",
    "strMeasure13": " ",
    "strMeasure14": " ",
    "strMeasure15": " ",
    "strMeasure16": " ",
    "strMeasure17": " ",
    "strMeasure18": " ",
    "strMeasure19": " ",
    "strMeasure20": " ",
    "strSource": ""
  },
  {
    "idMeal": "52904",
    "strMeal": "Beef Bourguignon",
    "strCategory": "Beef",
    "strArea": "French",
    "strInstructions": "Heat a large casserole pan and add 1 tbsp goose fat. Season the beef and fry until golden brown, about 3-5 mins, then turn over and fry the other side until the meat is browned all over, adding more fat if necessary. Do this in 2-3 batches, transferring the meat to a colander set over a bowl when browned.\r\nIn the same pan, fry the bacon, shallots or pearl onions, mushrooms, garlic and bouquet garni until lightly browned. Mix in the tomato purée and cook for a few mins, stirring into the mixture. This enriches the bourguignon and makes a great base for the stew. Then return the beef and any drained juices to the pan and stir through.\r\nPour over the wine and about 100ml water so the meat bobs up from the liquid, but isn’t completely covered. Bring to the boil and use a spoon to scrape the caramelised cooking juices from the bottom of the pan – this will give the stew more flavour.\r\nHeat oven to 150C/fan 130C/gas 2. Make a cartouche: tear off a square of foil slightly larger than the casserole, arrange it in the pan so it covers the top of the stew and trim away any excess foil. Then cook for 3 hrs. If the sauce looks watery, remove the beef and veg with a slotted spoon, and set aside. Cook the sauce over a high heat for a few mins until the sauce has thickened a little, then return the beef and vegetables to the pan.\r\nTo make the celeriac mash, peel the celeriac and cut into cubes. Heat the olive oil in a large frying pan. Tip in the celeriac and fry for 5 mins until it turns golden. Season well with salt and pepper. Stir in the rosemary, thyme, bay and cardamom pods, then pour over 200ml water, enough to nearly cover the celeriac. Turn the heat to low, partially cover the pan and leave to simmer for 25-30 mins.\r\nAfter 25-30 mins, the celeriac should be soft and most of the water will have evaporated. Drain away any remaining water, then remove the herb sprigs, bay and cardamom pods. Lightly crush with a potato masher, then finish with a glug of olive oil and season to taste. Spoon the beef bourguignon into serving bowls and place a large spoonful of the celeriac mash on top. Garnish with one of the bay leaves, if you like.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg",
    "strYoutube": "https://www.youtube.com/watch?v=SQnr4Z-7rok",
    "strIngredient1": "Goose Fat",
    "strIngredient2": "Beef Shin",
    "strIngredient3": "Bacon",
    "strIngredient4": "Challots",
    "strIngredient5": "Chestnut Mushroom",
    "strIngredient6": "Garlic Clove",
    "strIngredient7": "Bouquet Garni",
    "strIngredient8": "Tomato Puree",
    "strIngredient9": "Red Wine",
    "strIngredient10": "Celeriac",
    "strIngredient11": "Olive Oil",
    "strIngredient12": "Thyme",
    "strIngredient13": "Rosemary",
    "strIngredient14": "Bay Leaf",
    "strIngredient15": "Cardamom",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "3 tsp",
    "strMeasure2": "600g",
    "strMeasure3": "100g ",
    "strMeasure4": "350g",
    "strMeasure5": "250g",
    "strMeasure6": "2 sliced",
    "strMeasure7": "1",
    "strMeasure8": "1 tbs",
    "strMeasure9": "750 ml ",
    "strMeasure10": "600g",
    "strMeasure11": "2 tbs",
    "strMeasure12": "sprigs of fresh",
    "strMeasure13": "sprigs of fresh",
    "strMeasure14": "2",
    "strMeasure15": "4",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon"
  }
]

export {recipes};

